# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'hackFuture-NGshare' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    pod 'PromisesSwift'
    pod 'kintone-ios-sdk'
  # Pods for hackFuture-NGshare

end